# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Doctor')], null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Both')], default=1, verbose_name='sex'),
        ),
    ]
